repos:
# All GitHub specific hooks have been removed.
# You can add local hooks here if needed.
# Example of a local hook:
#  - repo: local
#    hooks:
#      - id: pylint
#        name: pylint
#        entry: pylint
#        language: system
#        types: [python]
#        args:
#          - "--rcfile=.pylintrc"
